import { Product, DevTool } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "vai",
    name: "VAI",
    tagline: "AI-powered video editor",
    description:
      "A full-featured video editing tool powered by AI. Trim, cut, colour grade, add effects and export in multiple formats. Designed for creators who want pro results without the learning curve.",
    category: "video",
    status: "live",
    price: 4999,
    priceLabel: "£49.99 / year",
    tags: ["video", "editing", "ai", "desktop"],
    featured: true,
  },
  {
    id: "screen-recorder",
    name: "Screen Recorder",
    tagline: "Record your screen for presentations & more",
    description:
      "Capture your screen, webcam, or both simultaneously. Perfect for tutorials, presentations, bug reports and demos. Supports HD recording, annotations and instant sharing.",
    category: "video",
    status: "live",
    price: 1999,
    priceLabel: "£19.99 one-off",
    tags: ["screen", "recording", "presentations", "desktop"],
    featured: true,
  },
  {
    id: "imageditor",
    name: "ImagEditor",
    tagline: "Retouch and restore old photos",
    description:
      "A powerful image retouching tool. Remove blemishes, restore old photographs, adjust colours, remove backgrounds and apply AI-enhanced filters. Simple enough for beginners, powerful enough for pros.",
    category: "image",
    status: "live",
    price: 2999,
    priceLabel: "£29.99 / year",
    tags: ["image", "photo", "retouching", "ai", "desktop"],
    featured: true,
  },
  {
    id: "3dbd",
    name: "3DBD",
    tagline: "Online multiplayer spatial game",
    description:
      "An immersive online multiplayer game set in a 3D spatial environment. Build, explore and compete with players worldwide. Real-time multiplayer with persistent worlds.",
    category: "game",
    status: "beta",
    tags: ["game", "multiplayer", "3d", "spatial", "online"],
    featured: false,
  },
  {
    id: "alittlecrookedhouse",
    name: "A Little Crooked House",
    tagline: "Exposing crooked businesses",
    description:
      "A community-driven website to discuss, report and expose dishonest business practices. Share your experiences, warn others and hold businesses accountable. AI-moderated for fairness.",
    category: "community",
    status: "live",
    tags: ["community", "reviews", "business", "consumer"],
    featured: false,
  },
  {
    id: "chessee",
    name: "Chessee",
    tagline: "Chess board scanner & AI coach",
    description:
      "Scan or upload a photo of any chess board and instantly get the best next move, full game analysis, or continue playing from that exact position. Powered by Stockfish and AI vision.",
    category: "ai",
    status: "live",
    price: 999,
    priceLabel: "£9.99 / month",
    tags: ["chess", "ai", "scanner", "game", "mobile"],
    featured: true,
  },
  {
    id: "devaint",
    name: "DevAInt",
    tagline: "AI agent for developers",
    description:
      "An intelligent AI agent built specifically for developers. Code review, refactoring suggestions, documentation generation, bug hunting and architecture advice — all in one place.",
    category: "ai",
    status: "beta",
    price: 1499,
    priceLabel: "£14.99 / month",
    tags: ["ai", "developer", "agent", "code", "productivity"],
    featured: true,
  },
  {
    id: "documentmaker",
    name: "Document Maker",
    tagline: "Scan hardcopies into editable documents",
    description:
      "Scan physical documents with your camera or upload images and convert them into fully editable Word, PDF or Google Docs format. OCR-powered with AI layout detection.",
    category: "productivity",
    status: "live",
    price: 1999,
    priceLabel: "£19.99 / year",
    tags: ["ocr", "scan", "documents", "productivity", "ai"],
    featured: false,
  },
  {
    id: "directorymaker",
    name: "Directory Maker",
    tagline: "Scrape the web, generate directory JSON",
    description:
      "Scrape any website or category and produce clean, structured JSON for content generation. Perfect for building directory listings, data pipelines and content sites at scale.",
    category: "utility",
    status: "live",
    price: 2999,
    priceLabel: "£29.99 / month",
    tags: ["scraping", "json", "directory", "data", "automation"],
    featured: false,
  },
  {
    id: "dups",
    name: "Dups",
    tagline: "Find duplicate images fast",
    description:
      "Scans your image library and finds duplicates using bitmap reduction comparison — not just filename matching. Works across formats, resolutions and slight edits. Reclaim your storage.",
    category: "utility",
    status: "live",
    price: 999,
    priceLabel: "£9.99 one-off",
    tags: ["images", "duplicates", "storage", "utility", "desktop"],
    featured: false,
  },
  {
    id: "endpointreader",
    name: "Endpoint Reader",
    tagline: "Test endpoints behind firewalls & VPNs",
    description:
      "A secure tool to test REST endpoints from behind corporate firewalls and VPNs. Supports GET, POST, PUT, DELETE with full config, encryption, token retention and security profiles.",
    category: "utility",
    status: "live",
    price: 3999,
    priceLabel: "£39.99 / year",
    tags: ["api", "testing", "endpoints", "security", "developer"],
    featured: true,
  },
  {
    id: "diyseller",
    name: "DIY Seller",
    tagline: "Sell your own stuff for less",
    description:
      "A peer-to-peer marketplace that undercuts the big platforms. List your items, set your price, keep more of your money. No hidden fees, no middlemen.",
    category: "marketplace",
    status: "live",
    tags: ["marketplace", "selling", "p2p", "ecommerce"],
    featured: false,
  },
  {
    id: "filecop",
    name: "FileCop",
    tagline: "Smart file copying by path structure",
    description:
      "Copy data intelligently by reading a file structure definition and only copying the paths you need. Supports filters, exclusions, scheduling and incremental sync.",
    category: "utility",
    status: "live",
    price: 1499,
    priceLabel: "£14.99 one-off",
    tags: ["files", "copy", "sync", "utility", "desktop"],
    featured: false,
  },
  {
    id: "freecarseller",
    name: "Free Car Seller",
    tagline: "Sell your car for free",
    description:
      "List your car for free and reach thousands of buyers. Monetised by advertising so you pay nothing. Full listing with photos, specs, history and direct buyer messaging.",
    category: "marketplace",
    status: "live",
    tags: ["cars", "selling", "marketplace", "free", "advertising"],
    featured: false,
  },
  {
    id: "fridge-door",
    name: "Fridge Door",
    tagline: "AI-powered social sharing for groups",
    description:
      "A social media app for user groups to share images, videos and notes — like post-it notes on a fridge door. AI-integrated for smart tagging, search and content suggestions.",
    category: "social",
    status: "beta",
    tags: ["social", "groups", "sharing", "ai", "mobile"],
    featured: true,
  },
  {
    id: "glasses",
    name: "Glasses Try-On",
    tagline: "Try glasses on virtually, buy with confidence",
    description:
      "Use your camera to virtually try on thousands of glasses frames. AI face mapping ensures accurate fit preview. Matched to retailers for direct purchase.",
    category: "ai",
    status: "coming_soon",
    tags: ["glasses", "ar", "ai", "retail", "fashion"],
    featured: false,
  },
  {
    id: "gotoglobe",
    name: "GoToGlobe",
    tagline: "Template site for directory listings",
    description:
      "A ready-to-deploy template for building directory listing websites. Clean design, SEO-optimised, with category filtering, search and map integration built in.",
    category: "directory",
    status: "live",
    price: 4999,
    priceLabel: "£49.99 one-off",
    tags: ["directory", "template", "website", "listing"],
    featured: false,
  },
  {
    id: "mapzter",
    name: "Mapzter",
    tagline: "Invert the property market with AI",
    description:
      "Buyers post where they want to live, what they'll pay and what they want — on a global map. Sellers and agents come to them. AI-matched, globally enabled, buyer-first property platform.",
    category: "property",
    status: "coming_soon",
    tags: ["property", "ai", "map", "real estate", "global"],
    featured: true,
  },
  {
    id: "musicmaker",
    name: "Music Maker",
    tagline: "Make your own music with AI",
    description:
      "Compose original music with AI assistance. Choose your style, instruments and mood — the AI generates tracks you can edit, layer and export. No music theory required.",
    category: "music",
    status: "coming_soon",
    tags: ["music", "ai", "composition", "creative"],
    featured: false,
  },
  {
    id: "musicmatcher",
    name: "Music Matcher",
    tagline: "Find similar music by sound, not genre",
    description:
      "Upload a track and find music that sounds similar — based on audio analysis, not genre tags or artist links. A classical piece might match a hip-hop track if the sound is right.",
    category: "music",
    status: "beta",
    price: 499,
    priceLabel: "£4.99 / month",
    tags: ["music", "ai", "audio", "discovery", "matching"],
    featured: true,
  },
  {
    id: "reactor",
    name: "Reactor",
    tagline: "React course with financial examples",
    description:
      "An online React course that teaches through real-world financial examples — dashboards, trading UIs, portfolio trackers and more. Practical, project-based learning.",
    category: "education",
    status: "live",
    price: 9999,
    priceLabel: "£99.99 lifetime",
    tags: ["react", "course", "finance", "education", "developer"],
    featured: false,
  },
  {
    id: "sohoho",
    name: "SoHoHo",
    tagline: "Directory listing for Soho, London",
    description:
      "The definitive directory for the Soho area of London. Restaurants, bars, shops, studios, agencies and more. Curated listings with reviews, opening hours and maps.",
    category: "directory",
    status: "live",
    tags: ["directory", "london", "soho", "local", "listings"],
    featured: false,
  },
  {
    id: "rugby27",
    name: "Rugby 27",
    tagline: "Rugby World Cup 2027 fan hub",
    description:
      "The go-to site for fans heading to Rugby World Cup 2027 in Australia. Fixtures, travel guides, accommodation, fan meetups, ticket info and live updates.",
    category: "community",
    status: "coming_soon",
    tags: ["rugby", "sport", "travel", "australia", "2027"],
    featured: false,
  },
  {
    id: "triptrapping",
    name: "TripTrapping",
    tagline: "Van & travel community across Europe",
    description:
      "A community platform for van lifers and travellers to connect, share routes, tips and meetups as they travel — starting in Europe. AI-powered route suggestions and travel alerts.",
    category: "travel",
    status: "beta",
    tags: ["travel", "van life", "community", "europe", "ai"],
    featured: true,
  },
  {
    id: "vanhire",
    name: "VanHire",
    tagline: "Hire my camper van",
    description:
      "A peer-to-peer camper van hire platform. List your van, set your availability and price, and connect with travellers looking for their next adventure.",
    category: "travel",
    status: "coming_soon",
    tags: ["van", "hire", "travel", "p2p", "camper"],
    featured: false,
  },
  {
    id: "jsoneditor",
    name: "JSON Editor",
    tagline: "Load, reorder and edit large JSON files",
    description:
      "A desktop tool for working with large JSON files. Load multi-megabyte files without freezing, reorder nodes via drag and drop, edit values inline, search and filter keys, and export clean formatted or minified output.",
    category: "utility",
    status: "live",
    price: 1499,
    priceLabel: "£14.99 one-off",
    tags: ["json", "editor", "developer", "utility", "desktop"],
    featured: false,
  },
  {
    id: "winfloss",
    name: "WinFloss",
    tagline: "Give your computer a good clean",
    description:
      "A Windows utility to clean, optimise and speed up your PC. Remove junk files, fix registry issues, manage startup programs and monitor system health. Like CCleaner but smarter.",
    category: "utility",
    status: "wip",
    tags: ["windows", "cleaner", "utility", "optimise", "desktop"],
    featured: false,
  },
];

export const DEV_TOOLS: DevTool[] = [
  { id: "github", name: "GitHub", url: "https://github.com", category: "git", color: "orange" },
  { id: "azure", name: "Azure", url: "https://portal.azure.com", category: "cloud", color: "blue" },
  { id: "aws", name: "AWS", url: "https://console.aws.amazon.com", category: "cloud", color: "yellow" },
  { id: "gcloud", name: "Google Cloud", url: "https://console.cloud.google.com", category: "cloud", color: "red" },
  { id: "kiro", name: "Kiro", url: "https://kiro.dev", category: "ide", color: "cyan" },
  { id: "antigravity", name: "Anti-Gravity", url: "https://anti-gravity.dev", category: "ide", color: "purple" },
  { id: "supabase", name: "Supabase", url: "https://supabase.com/dashboard", category: "database", color: "green" },
  { id: "neon", name: "Neon", url: "https://console.neon.tech", category: "database", color: "green" },
  { id: "vercel", name: "Vercel", url: "https://vercel.com/dashboard", category: "hosting", color: "green" },
  { id: "railway", name: "Railway", url: "https://railway.app/dashboard", category: "hosting", color: "purple" },
];

export const CATEGORY_COLORS: Record<string, string> = {
  video: "cyan",
  image: "pink",
  productivity: "blue",
  game: "purple",
  social: "yellow",
  ai: "cyan",
  directory: "indigo",
  marketplace: "orange",
  education: "green",
  utility: "red",
  travel: "green",
  music: "pink",
  property: "indigo",
  community: "yellow",
};

export const STATUS_LABELS: Record<string, string> = {
  live: "Live",
  coming_soon: "Coming Soon",
  wip: "WIP",
  beta: "Beta",
};

export const STATUS_COLORS: Record<string, string> = {
  live: "green",
  coming_soon: "yellow",
  wip: "orange",
  beta: "cyan",
};
